### ISSUE TITLE
cant see the space ship

### ISSUE THREAD

**Issue by kwatman** [SebLague/Solar-System#1]
i downloaded the projetc and ran it in unity. everything works. but I cannot see the space ship. it is invisible. How do I fix this ?

**Comment by SebLague** [comment]
You'll need to have blender installed from https://www.blender.org/
When I have a moment I'll export the model to fbx to remove the dependency

**Comment by Delofon** [comment]
If this anyway happens, just open the models folder in explorer and just drag the "Space Ship" model into project window.
