### ISSUE TITLE
How can I have two diffrent ships?

### ISSUE THREAD

**Issue by WilleLX1** [SebLague/Solar-System#42]
If I duplicate the spaceship, I only get my editor to freeze, any help would be appreciated.

**Comment by Delofon** [comment]
By far the weirdest issue... do you turn on the play mode? If not, then I can only question my sanity. When I tried duplicating the ship, the worst thing that happened was various scripts getting passed reference to the "wrong" ship. (this probably calls for script rewriting as it may produce some bugs ;p)
