### ISSUE TITLE
How to go about having multiple planets of the same generation (Constant Companion) with different settings?

### ISSUE THREAD

**Issue by Panicat** [SebLague/Solar-System#47]
Title should be self explanatory. Changing the shape or shading seed on one planet changes all planets that use the same generation settings. Would it be easy to have multiple Constant Companion planets with different settings?

Duplicating the celestial body settings still seems to affect the same material for the planet and I'm not quite sure how this works. Thanks!

**Comment by Delofon** [comment]
CelestialBodyGenerator uses scriptable objects to define planets' settings. You'd better be off creating (or duplicating) a new planet settings asset and changing settings there.

**Comment by Panicat** [comment]
Thank you. I just needed to duplicate all the files: Celestial Body Settings, Shading, Shape, and Material. Then assign them accordingly. Stupid reason to make an issue here, but closed!
